export default {
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT",
	SET_KEYS: "SET_KEYS",
	SET_SELECTED: "SET_SELECTED",
	SET_RECORDS: "SET_RECORDS",
	SEARCH_RECORDS: "SEARCH_RECORDS",
	SET_SEARCH_TERM: "SET_SEARCH_TERM"
};
